### ISSUE TITLE
Create staticLayers Module

### ISSUE THREAD

**Issue by mbelem** [maretec/aguamod#1]

**Comment by flaviosantosmaretec** [comment]
Os comportamentos referentes às chamadas de cada layer têm que estar mais bem definidos. Abrindo uma layer e depois outra parece baralhar logo o Action Server, em qual a layer que devia ir buscar. 

Os nomes das layers do Aguamod Plus não podem ser Demarcaciones_simplified_tal_nãoseique, porque a função do layout createtableDemarc, precisa do nome demarcaciones_simplified, o que significa que ele vai gerar um layout para as layers do AguamodPlus o que não é para acontecer.
