### ISSUE TITLE
Isolate "timeBar" behaviour

### ISSUE THREAD

**Issue by mbelem** [maretec/aguamod#2]

**Comment by flaviosantosmaretec** [comment]
Um problema muito grave em relação aos botões do forwardMonth e do backwardMonth! Quanto está numa layer operacional (meteorologia ou hidrologia) e se mandarmos o tempo para trás um mês, ele não vai buscar os resultados! Ou seja, o clicar para andar para a frente ou para trás um mês não está a fazer nenhum pedido ao Server.

**Comment by flaviosantosmaretec** [comment]
Se calhar podemos considerar retirar os botões dos meses.
