### ISSUE TITLE
Isolate Demarc, subsistemas and reservoirs

### ISSUE THREAD

**Issue by mbelem** [maretec/aguamod#4]

**Comment by flaviosantosmaretec** [comment]
Reservatórios não precisam de aparecer para o objetivo final do projeto. Mas não vamos apagá-los! Quanto muito podemos comentar as layers no DomainConfig. Deu trabalho a associar os modelos operacionais de reservatório a cada ponto da shapefile e podem ainda ser úteis para mostrar a clientes futuros.
